gce-xfstests ltm: authenticate requests using 15 character password
As the /gce-xfstests POST endpoint will be used to launch child VMs and
is available to the public internet, the LTM needs to authenticate
requests coming to the endpoint. This change adds a login requirement
to the gce-xfstests POST endpoint.

gce-xfstests setup will generate a 15 character password using pwgen
and upload it to $GS_BUCKET/ltm-pass. Alternatively, the user can
manually upload the password.

The launch-ltm command will fail if the user does not have an
ltm-pass in their bucket. The launch-ltm command will also
download this password to a local hidden file.

Using the --ltm option on the command line will automatically
authenciate the request by logging in before making the request, so no
password needs to be manually entered.

Signed-off-by: Jason Liu <liujason@google.com>
Change-Id: I1d4b7e21501fe119593fd9c247dc129fca217af5

diff --git a/kvm-xfstests/util/gce-ltm-funcs b/kvm-xfstests/util/gce-ltm-funcs
--- a/kvm-xfstests/util/gce-ltm-funcs
+++ b/kvm-xfstests/util/gce-ltm-funcs
@@ -1,27 +1,50 @@
+. $DIR/.ltm_instance
 
+# The hostname has to match the common name field of the certificate, as set
+# in util/gce-do-setup when running openssl to create a self-signed cert.
+# curl will fail otherwise, stating that the common names do not match.
+LTM_HOSTNAME="a.$GCE_PROJECT.gce-xfstests"
+
+function ltm_post_json() {
+    curl --cacert $GCE_LTM_SERVER_CERT -H "Content-Type: application/json" \
+	--resolve "$LTM_HOSTNAME:443:$GCE_LTM_EXT_IP" -X POST "$@"
+}
+
+function ltm_post_failed() {
+    if gcloud compute instances describe "xfstests-ltm" &> /dev/null; then
+	echo "The ltm instance seems to be running. Try deleting the"
+	echo "$DIR/.ltm_instance file and re-running launch-ltm to recreate"
+	echo "the file. If the issue persists, try relaunching the LTM"
+	echo "If configuration changes have been made, it may be necessary"
+	echo "to delete and re-launch the LTM."
+    else
+	echo "The ltm doesn't seem to be running. Try launching the ltm"
+	echo "instance with launch-ltm. This will recreate the"
+	echo ".ltm_instance file."
+    fi
+
+
+}
 function send_to_ltm() {
-    . $DIR/.ltm_instance
     local cmd_to_send=$1
 
-    # Validate certificate
-    curl --cacert $GCE_LTM_SERVER_CERT -H "Content-Type: application/json" \
-	-d "{\"orig_cmdline\": \"$cmd_to_send\"}" \
-	--resolve "a.$GCE_PROJECT.gce-xfstests:443:$GCE_LTM_EXT_IP" \
-	-X POST "https://a.$GCE_PROJECT.gce-xfstests/gce-xfstests"
+    # just create a new login session and store it in the cookie
+    ltm_post_json -c $DIR/.ltm_cookie -d "{\"password\":\"$GCE_LTM_PWD\"}" \
+        "https://$LTM_HOSTNAME/login"
+
+    if [ ! $? = 0 ]; then
+	echo "Login failed."
+	ltm_post_failed
+	return 1
+    fi
+
+    ltm_post_json -b $DIR/.ltm_cookie -d "{\"orig_cmdline\": \"$cmd_to_send\"}" \
+	"https://$LTM_HOSTNAME/gce-xfstests"
 
     if [ $? != 0 ]; then
 	echo "Request failed."
-	if gcloud compute instances describe "xfstests-ltm" &> /dev/null; then
-	    echo "The ltm instance seems to be running. Try deleting the"
-	    echo "$DIR/.ltm_instance file and re-running launch-ltm to recreate"
-	    echo "the file. If the issue persists, try relaunching the LTM"
-	else
-	   echo "The ltm doesn't seem to be running. Try launching the ltm"
-	   echo "instance with launch-ltm. This will recreate the"
-	   echo ".ltm_instance file."
-	fi
+	ltm_post_failed
 	return 1
     fi
 
 }
-
