gce-xfstests: use iam instead of acl to set bucket permissions
When uniform bucket-level access is enabled, acl permissions are not in
effect. Upate setting of bucket permissions to use gsutil iam command
isntead when uniform bucket-level access is set on a project.

Signed-off-by: Leah Rumancik <leah.rumancik@gmail.com>

diff --git a/kvm-xfstests/util/gce-do-setup b/kvm-xfstests/util/gce-do-setup
--- a/kvm-xfstests/util/gce-do-setup
+++ b/kvm-xfstests/util/gce-do-setup
@@ -145,7 +145,18 @@ function SetupServiceAccount () {
 	    exit 1
 	fi
     fi
-    gsutil acl ch -u "${srv_acct}:W" gs://$GS_BUCKET
+
+    # when uniform bucket-level access is enabled, acl does not work
+    if gsutil acl get gs://$GS_BUCKET &> /dev/null -eq 0; then
+	    # set via acl
+	    gsutil acl ch -u "${srv_acct}:W" gs://$GS_BUCKET
+    else
+	    # set via iams
+	    if ! gsutil iam ch "serviceAccount:${srv_acct}:legacyBucketWriter" \
+		    gs://$GS_BUCKET &> /dev/null; then
+		echo "Error setting up gs://$GS_BUCKET write permissions for ${srv_acct}"
+	    fi
+    fi
 }
 
 function SetupServiceAccountCloudBuild () {
