kvm-xfstests,test-appliance: add kvm-xfstests syz command
Add the new command "kvm-xfstests syz <repro>", where "<repro>" can
either be a C source file, a syz file, an executable file, or a URL to
C or SYZ reproducer file downloaded from the Syzkaller dashboard.

Signed-off-by: Theodore Ts'o <tytso@mit.edu>

diff --git a/kvm-xfstests/util/parse_cli b/kvm-xfstests/util/parse_cli
--- a/kvm-xfstests/util/parse_cli
+++ b/kvm-xfstests/util/parse_cli
@@ -5,6 +5,22 @@ SNAPSHOT=",snapshot=on"
 DO_AEX="yes"
 API="1.3"
 
+ourtmp=$(mktemp --tmpdir --directory xfstests-cli.XXXXXXXX)
+done_cleanup=false
+
+trap "_cleanup; exit 1" 0 1 2 3 15
+
+_cleanup()
+{
+    if $done_cleanup
+    then
+	:
+    else
+	rm -rf "$ourtmp"
+	done_cleanup=true
+    fi
+}
+
 # Is the invoked interface (kvm-xfstests, gce-xfstests, etc.) in the given list?
 flavor_in ()
 {
@@ -29,6 +45,7 @@ print_help ()
     echo "Usage: $PROG [<OPTIONS>] <test> ..."
     echo "Usage: $PROG [<OPTIONS>] -g <group> ..."
     echo "Usage: $PROG [<OPTIONS>] shell|maint"
+    echo "Usage: $PROG [<OPTIONS>] syz <repro>"
     echo ""
     echo "Common options are:"
     echo "	-a		- Disable auto-exclude; run all tests"
@@ -297,6 +314,7 @@ while (( $# >= 1 )); do
 	    supported_flavors kvm gce
 	    UPDATE_XFSTESTS_TAR=yes
 	    UPDATE_XFSTESTS=yes
+	    UPDATE_XFSTESTS_DIR="$DIR/.."
 	    ;;
 	--update-xfstests)
 	    supported_flavors kvm gce
@@ -306,6 +324,7 @@ while (( $# >= 1 )); do
 		exit 1
 	    fi
 	    UPDATE_XFSTESTS=yes
+	    UPDATE_XFSTESTS_DIR="$DIR/.."
 	    ;;
 	--update-files)
 	    supported_flavors kvm gce
@@ -495,6 +514,88 @@ while (( $# >= 1 )); do
 	    ;;
 	full)
 	    FSTESTSET="$FSTESTSET,-g,auto"
+	    ;;
+	syz)
+	    supported_flavors kvm
+	    shift
+	    if test "$1"x = "x" ; then
+		echo "Missing syzkaller repro"
+		print_help
+		exit 1
+	    fi
+	    mkdir -p "$ourtmp/xfstests/tests"
+	    cp -r "$DIR/test-appliance/syz" "$ourtmp/xfstests/tests"
+	    repro="$1"
+	    case "$repro" in
+		https://syzkaller*repro.syz*)
+		    curl -o "$ourtmp/repro.syz" "$repro"
+		    ed "$ourtmp/repro.syz" >& /dev/null <<EOF
+1i
+# Downloaded from $repro
+.
+w
+q
+EOF
+		    repro="$ourtmp/repro.syz"
+		    save_copy="/tmp/$USER-downloaded-repro.syz"
+		    cp $repro "$save_copy"
+		    echo "Saved downloaded copy at $save_copy"
+		    ;;
+		https://syzkaller*repro.c*)
+		    curl -o "$ourtmp/repro.c" "$repro"
+		    ed "$ourtmp/repro.c" >& /dev/null <<EOF
+1i
+// Downloaded from $repro
+.
+w
+q
+EOF
+		    repro="$ourtmp/repro.c"
+		    save_copy="/tmp/$USER-downloaded-repro.c"
+		    cp $repro "$save_copy"
+		    echo "Saved downloaded copy at $save_copy"
+		    ;;
+		https://*)
+		    echo "Unknown URL: $repro"
+		    exit 1
+		    ;;
+	    esac
+	    case "$repro" in
+		*.c)
+		    if test -f "$repro" ; then
+			exe="$ourtmp/xfstests/tests/syz/001.exe"
+			if ! gcc -o $exe -static $repro -lpthread ; then
+			    echo "Failed to build $repro"
+			    exit 1;
+			fi
+		    else
+			echo "Reproduction file $repro not found"
+			exit 1
+		    fi
+		    ;;
+		*.syz)
+		    if ! test -f "$repro" ; then
+			echo "Reproduction file $repro not found"
+			exit 1
+		    fi
+		    cp "$repro" "$ourtmp/xfstests/tests/syz/001.syz"
+		    ;;
+		*)
+		    if ! test -f "$repro" ; then
+			echo "Reproduction file $repro not found"
+			exit 1
+		    fi
+		    if ! test -x "$repro" ; then
+			echo "Reproduction file $repro not executable"
+			exit 1
+		    fi
+		    cp "$repro" "$ourtmp/xfstests/tests/syz/001.exe"
+		    ;;
+	    esac
+	    tar -C "$ourtmp" -cvz -f "$ourtmp/extra-tests.tar.gz" xfstests \
+		>& /dev/null
+	    UPDATE_EXTRA_TESTS=yes
+	    FSTESTSET="$FSTESTSET,syz/001"
 	    ;;
 	launch)
 	    supported_flavors gce
