kvm-xfstests, gce-xfstests: validate the test name before launching the VM
Signed-off-by: Theodore Ts'o <tytso@mit.edu>

diff --git a/kvm-xfstests/util/parse_cli b/kvm-xfstests/util/parse_cli
--- a/kvm-xfstests/util/parse_cli
+++ b/kvm-xfstests/util/parse_cli
@@ -2,6 +2,17 @@ FSTESTCFG=all
 SNAPSHOT=",snapshot=on"
 DO_AEX="yes"
 
+validate_test_name()
+{
+    case "$1" in
+	btrfs*|cifs*|ext4*|generic*|shared*|udf*|xfs*) ;;
+	*)
+	    echo "Invalid test name: $1"
+	    exit 1
+	    ;;
+    esac
+}
+
 while [ "$1" != "" ]; do
   case $1 in
     -a)
@@ -108,6 +119,7 @@ while [ "$1" != "" ]; do
       ARG="cmd=ver"
       ;;
     *)
+      validate_test_name "$1"
       FSTESTSET="$FSTESTSET,$1"
       ;;
   esac
