kvm-xfstests: teach --kernel to accept the kernel source directory
Instead of requiring the user to type:

./kvm-xfstests --kernel /build/linux/arch/x856/boot/bzImage smoke

allow the shortcut of

./kvm-xfstests --kernel /build/linux smoke

instead.

Signed-off-by: Theodore Ts'o <tytso@mit.edu>

diff --git a/kvm-xfstests/util/parse_cli b/kvm-xfstests/util/parse_cli
--- a/kvm-xfstests/util/parse_cli
+++ b/kvm-xfstests/util/parse_cli
@@ -117,6 +117,15 @@ if test "$DO_AEX" = yes ; then
     FSTESTOPT="$FSTESTOPT,aex"
 fi
 
+if test -d "$KERNEL" ; then
+    KERNEL=$KERNEL/arch/x86/boot/bzImage
+fi
+
+if ! test -f "$KERNEL"; then
+     echo "$KERNEL: kernel not found"
+     exit 1
+fi
+
 FSTESTOPT=$(echo $FSTESTOPT | sed -e 's/^,//')
 
 if test "$SKIP_LOG" = no ; then
