run-fstests: get/infer the architecture from the kernel file
When uploading a file using "gce-xfstests upload-kernel", infer the
architecture from the kernel to be uploaded, and set it in the Google
Cloud Storage metadata.

When running a test, get the architecture from the kernel file, and if
the architecture is explicitly specified, check to make sure the
kernel architecture matches the architecture specified on the command
line.  If the architecture is not explicitly specified, use the
architecture of the kernel as the architecture that should be used for
the test.

The net result of this change is that if an arm64 kernel is uploaded,
for example, using the command "gce-xfstests --arm64 upload-kernel",
the uploaded kernel will be tagged with the appropriate metadata, and
so when a test is launched via "gce-xfstests --kernel
gs://$GS_BUCKET/kernel.deb", the architecture type arm64 will be
automatically inferred, and an ARM64 VM will be used.

Similarly, if kvm-xfstests is passed an explicit kernel --- for
example "kvm-xfstests --kernel /build/ext4-arm64/arch/arm64/boot/Image
shell" qemu-system-aarch64 will be automatically used.

Signed-off-by: Theodore Ts'o <tytso@mit.edu>

diff --git a/run-fstests/util/arch-funcs b/run-fstests/util/arch-funcs
--- a/run-fstests/util/arch-funcs
+++ b/run-fstests/util/arch-funcs
@@ -74,3 +74,65 @@ function set_cross_compile ()
 	    ;;
     esac
 }
+
+function get_kernel_file_info () {
+    local is_gs=
+    KERNEL_ARCH=
+    KERNEL_VERSION=
+    KERNEL="$1"
+
+    case "$KERNEL" in
+	gs://*)
+	    is_gs=yes
+	    ;;
+    esac
+
+    if test -n "$is_gs" ; then
+	local f=$(mktemp --tmpdir gs_stat_XXXXXX)
+	if gsutil stat "$KERNEL" > "$f" ; then
+	    cat "$f" | sed -e '1,/^    Metadata:/d' | \
+		sed -e '/^    [A-Z]/,$d' > "$f.new"
+	    mv "$f.new" "$f"
+	else
+	    rm -f "$f"
+	    exit 1
+	fi
+	KERNEL_ARCH=$(cat "$f" | grep arch= | sed -e 's/^ *arch=//' -e 's/: *$//')
+	KERNEL_VERSION=$(cat "$f" | grep ver= | sed -e 's/^ *ver=//' -e 's/: *$//')
+	rm -f "$f"
+    else
+	if test ! -f "$KERNEL" ; then
+	    echo "get-kernel-arch: file not found: $KERNEL" >&2
+	    exit 1
+	fi
+	info=$(file "$KERNEL" | sed -e "s;$KERNEL: ;;")
+	case "$info" in
+	    "Linux kernel"*)
+		KERNEL_ARCH=$(echo $info | tr A-Z a-z |awk '{print $3}')
+		d=$(dirname $(dirname $(dirname $(dirname "$KERNEL"))))
+		if test -f "$d/.git_version" ; then
+		    KERNEL_VERSION=$(cat "$d/.git_version")
+		fi
+		if test -f "$d/.config" ; then
+		    if test "$KERNEL_ARCH" = "x86" ; then
+			KERNEL_ARCH=$(head "$d/.config" | grep "^#.*Kernel Configuration" | \
+				   awk '{print $2}' | sed -e 's;Linux/;;')
+			if test "$KERNEL_ARCH" = "x86_64" ; then
+			    KERNEL_ARCH=amd64
+			fi
+		    fi
+		fi
+		;;
+	    "Debian binary package"*)
+		KERNEL_ARCH=$(dpkg -I "$KERNEL" | grep "^ Architecture: " | \
+			   awk '{print $2}')
+		KERNEL_VERSION=$(dpkg -I "$KERNEL" | grep "^ Version: " | \
+			  awk '{print $2}')
+		;;
+	    *)
+		echo "get-kernel-arch $i is not a kernel" >&2
+		echo "$info"
+		exit 1
+	esac
+    fi
+}
