test-appliance: add support for the Phoronix Test Suite
The gce-create-image script will optionally install a specific version
of the Phoronix Test Suite.  For example, to install the version 9.0.1
of the PTS, run: "gce-xfstests create-image --phoronix 9.0.1"

Be sure to mount a file system to be used for the benchmark on top of
/var/lib/phoronix-test-suite before installing or running any
benchmarks using PTS.

Signed-off-by: Theodore Ts'o <tytso@mit.edu>

diff --git a/kvm-xfstests/test-appliance/gce-create-image b/kvm-xfstests/test-appliance/gce-create-image
--- a/kvm-xfstests/test-appliance/gce-create-image
+++ b/kvm-xfstests/test-appliance/gce-create-image
@@ -91,6 +91,9 @@ do
 	--buster)
 	    setup_for_buster
 	    ;;
+	--phoronix) shift
+	    PHORONIX="$1"
+	    ;;
 	-I) shift
 	    ROOT_FS="$1"
 	    BLD_INST="xfstests-bld-$1"
@@ -108,6 +111,17 @@ done
 GS_SCRIPT=gs://$GS_BUCKET/create-image/gce-xfstests-bld.sh
 METADATA="startup-script-url=$GS_SCRIPT suite=$SUITE"
 GCE_MACHTYPE=n1-standard-1
+
+if test -n "${PHORONIX}" ; then
+    url="http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_${PHORONIX}_all.deb"
+    code=$(curl -o /dev/null --silent --head --write-out '%{http_code}' $url)
+    if test $code -ne 200 ; then
+	echo "Can't find Phoronix version ${PHORONIX}"
+	echo "  (url $url returned http code $code)"
+	exit 1
+    fi
+    METADATA="$METADATA phoronix=${PHORONIX}"
+fi
 
 td=$(mktemp -d /tmp/gce-create.XXXXXXXX)
 
