test-appliance: improve image generation for chroot tar files
With Debian Stretch, systemctl has a DT_RPATH for its systemd shared
library, and fakechroot doesn't seem to handle this correctly.  So
this causes debootstrap to fake when running gen-image --out-tar using
fakechroot.  So teach gen-image so it can work without using
fakechroot if it is running with root privileges.

Also fix gen-image so that it can work correctly when using Qemu user
emulation (e.g., when we are building an armhf binary image on an x86
host platform).

Signed-off-by: Theodore Ts'o <tytso@mit.edu>

diff --git a/kvm-xfstests/test-appliance/gen-image b/kvm-xfstests/test-appliance/gen-image
--- a/kvm-xfstests/test-appliance/gen-image
+++ b/kvm-xfstests/test-appliance/gen-image
@@ -21,6 +21,18 @@ if test -r config.custom ; then
    . $(pwd)/config.custom
 fi
 
+is_native_chroot()
+{
+    DEBIAN_ARCH="$(dpkg --print-architecture)"
+    case "$(uname -m)" in
+    x86_64)	[[ $DEBIAN_ARCH = amd64 || $DEBIAN_ARCH = i386 ]] ;;
+    aarch64)	[[ $DEBIAN_ARCH = arm64 || $DEBIAN_ARCH = armhf ]] ;;
+    arm)	[[ $DEBIAN_ARCH = armhf ]] ;;
+    ppc64le)	[[ $DEBIAN_ARCH = ppc64el ]] ;;
+    *)		[[ $DEBIAN_ARCH = "$(uname -m)" ]] ;;
+    esac
+}
+
 while [ "$1" != "" ]; do
   case $1 in
     --save_raw_root)
@@ -78,12 +90,12 @@ if test -n "$DO_LOG" ; then
     fi
 fi
 
-if test -n "$OUT_TAR" ; then
+if test -n "$OUT_TAR" -a "$EUID" -ne 0 ; then
+    export DO_FAKECHROOT=yes
+fi
+
+if test -n "$DO_FAKECHROOT" ; then
     if test "$FAKECHROOT" != "true" ; then
-	if test "$EUID" -eq 0 ; then
-	    echo "This script MUST NOT be run as root with --out_tar"
-	    exit 1;
-	fi
 	set -- "${SAVE_ARGS[@]}"
 	exec fakechroot $0 "$@"
     fi
@@ -128,7 +140,7 @@ update_xfstests()
 
 fix_symlinks()
 {
-    if test -n "$OUT_TAR"; then
+    if test -n "$DO_FAKECHROOT"; then
 	symlinks -crd rootdir
     fi
 }
@@ -142,7 +154,7 @@ finalize_rootfs()
 
 cleanup_rootdir()
 {
-    if test -z "$OUT_TAR"; then
+    if test -z "$DO_FAKECHROOT"; then
 	if test -d $ROOTDIR ; then
 	    umount $ROOTDIR/var/cache/apt/archives
 	    umount $ROOTDIR/var/lib/apt/lists
@@ -163,12 +175,29 @@ cleanup_rootdir()
     fi
 }
 
+run_in_chroot()
+{
+    echo "Running in chroot: $1"
+    # Note: we execute the command in a login shell rather than execute it
+    # directly because this makes the $PATH get set up correctly.
+    DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
+	LC_ALL=C LANGUAGE=C LANG=C chroot "$ROOTDIR" /bin/sh -l -c "$1"
+}
+
 cleanup_on_abort()
 {
     cleanup_rootdir
     rm -f "$RAW_ROOT_FS"
     trap - INT TERM
 }
+
+if test -n "$OUT_TAR" ; then
+    if test $DO_UPDATE = "yes" ; then
+	echo "Incompatible options: --out-tar and --update"
+	exit 1
+    fi
+    rm -rf "$ROOTDIR"
+fi
 
 mkdir -p $ROOTDIR
 if test $DO_UPDATE = "yes" ; then
@@ -182,10 +211,25 @@ if test $DO_UPDATE = "yes" ; then
    exit 0
 fi
 
+if ! is_native_chroot ; then
+    case "$DEBIAN_ARCH" in
+	armhf)		QEMU=/usr/bin/qemu-arm-static ;;
+	arm64)		QEMU=/usr/bin/qemu-aarch64-static ;;
+	ppc64el)	QEMU=/usr/bin/qemu-ppc64le-static ;;
+	*)		QEMU="/usr/bin/qemu-$DEBIAN_ARCH-static" ;;
+    esac
+    if ! test -x $QEMU ; then
+	echo "Can't find qemu interpreter for non-native gen-image"
+#	cleanup_on_abort
+#	exit 1
+    fi
+    FOREIGN="--foreign"
+fi
+
 mkdir -p var.cache.apt.archives
 mkdir -p var.lib.apt.lists
 mkdir -p debs
-if test -z "$OUT_TAR"; then
+if test -z "$DO_FAKECHROOT"; then
    cp /dev/null $RAW_ROOT_FS
    mke2fs -t ext4 -O ^has_journal -Fq $RAW_ROOT_FS 1g
    mount -t ext4 -o loop $RAW_ROOT_FS $ROOTDIR
@@ -195,7 +239,7 @@ mkdir -p $ROOTDIR/var/lib/apt/lists
 mkdir -p $ROOTDIR/debs
 mkdir -p $ROOTDIR/imgdir
 mkdir -p $ROOTDIR/vtmp
-if test -z "$OUT_TAR"; then
+if test -z "$DO_FAKECHROOT"; then
    mount --bind var.cache.apt.archives $ROOTDIR/var/cache/apt/archives
    mount --bind var.lib.apt.lists $ROOTDIR/var/lib/apt/lists
    mount --bind debs $ROOTDIR/debs
@@ -207,20 +251,30 @@ else
    export FAKECHROOT_CMD_SUBST=/usr/bin/chfn=/bin/true
 fi
 trap cleanup_on_abort INT TERM
-debootstrap --variant=minbase --include=$PACKAGES $EXCLUDE $ARCH $SUITE $ROOTDIR $MIRROR $DIR/debootstrap.script
+debootstrap --variant=minbase --include=$PACKAGES $EXCLUDE $ARCH \
+	    $FOREIGN $SUITE $ROOTDIR $MIRROR $DIR/debootstrap.script
 if test $? -ne 0 ; then
     echo "Deboostrap failed, aborting."
     cleanup_on_abort
     exit 1
 fi
+if test -n "$QEMU" ; then
+    cp $QEMU $ROOTDIR/usr/bin/
+    run_in_chroot "/debootstrap/debootstrap --second-stage"
+    run_in_chroot "dpkg --configure -a"
+    mkdir -p "$ROOTDIR/run/shm"
+    chmod 1777 "$ROOTDIR/run/shm"
+fi
 ./get-backports-pkgs "$SUITE" "$ROOTDIR"
-DEBS=$(while read pkg path; do echo $path ; done <"/$ROOTDIR/debootstrap/debpaths")
-chroot $ROOTDIR dpkg --ignore-depends=e2fsprogs -i $DEBS
+if test -f "$ROOTDIR/debootstrap/debpaths" ; then
+    DEBS=$(while read pkg path; do echo $path ; done <"$ROOTDIR/debootstrap/debpaths")
+    run_in_chroot "dpkg --ignore-depends=e2fsprogs -i $DEBS"
+fi
 rm -rf "$ROOTDIR/debootstrap"
 DEBS=$(find debs -name \*.deb)
 if test -n "$DEBS"
 then
-    chroot $ROOTDIR dpkg --ignore-depends=e2fsprogs -i $DEBS
+    run_in_chroot "dpkg --ignore-depends=e2fsprogs -i $(echo $DEBS)"
 fi
 update_xfstests
 for i in vda vdb vdc vdd vde vdf results
@@ -245,17 +299,17 @@ sed -i -e '/ExecStart/s/agetty/agetty -a root/' \
 sed -i -e '/ExecStart/s/agetty/agetty -a root/' \
     -e 's/After=rc.local.service/After=network.target/' \
 	$ROOTDIR/etc/systemd/system/telnet-getty@.service
-chroot $ROOTDIR dpkg --purge gcc-4.7-base gcc-4.8-base
-chroot $ROOTDIR systemctl enable kvm-xfstests.service
-chroot $ROOTDIR systemctl enable telnet-getty@ttyS1.service
-chroot $ROOTDIR systemctl enable telnet-getty@ttyS2.service
-chroot $ROOTDIR systemctl enable telnet-getty@ttyS3.service
+run_in_chroot "dpkg --purge gcc-4.7-base gcc-4.8-base"
+run_in_chroot "systemctl enable kvm-xfstests.service"
+run_in_chroot "systemctl enable telnet-getty@ttyS1.service"
+run_in_chroot "systemctl enable telnet-getty@ttyS2.service"
+run_in_chroot "systemctl enable telnet-getty@ttyS3.service"
 find $ROOTDIR/usr/share/doc -type f | grep -v copyright | xargs rm
 find $ROOTDIR/usr/share/doc -mindepth 2 -type l | xargs rm
 find $ROOTDIR/usr/share/doc -type d | xargs rmdir --ignore-fail-on-non-empty -p
 rm -rf $ROOTDIR/usr/share/man
 find $ROOTDIR/var/log -type f | xargs rm
-if test -n "$OUT_TAR"; then
+if test -n "$DO_FAKECHROOT"; then
     rm -f $ROOTDIR/dev $ROOTDIR/proc
     mkdir $ROOTDIR/dev $ROOTDIR/proc
     mknod -m 622 $ROOTDIR/dev/console c 5 1
@@ -297,24 +351,34 @@ fi
 rm -rf $ROOTDIR/var/cache/apt/archives/partial \
 	$ROOTDIR/var/lib/apt/lists/partial
 if test -n "$OUT_TAR"; then
-    (cd $ROOTDIR/var/cache/apt/archives ; \
-     for i in * ; do \
-	 if test ! -f $DIR/var.cache.apt.archives/$i ; then \
-	     echo caching $i ; \
-	     ln $i $DIR/var.cache.apt.archives/ ; \
-	 fi ; \
-     done)
-    (cd $ROOTDIR/var/lib/apt/lists ; \
-     for i in * ; do \
-	 if test ! -f $DIR/var.lib.apt.lists/$i ; then \
-	     echo caching $i ; \
-	     ln $i $DIR/var.lib.apt.lists/ ; \
-	 fi ; \
-     done)
-    find $ROOTDIR/var/cache/apt/archives $ROOTDIR/var/lib/apt/lists \
-	 $ROOTDIR/debs -type f | xargs rm
-    rmdir $ROOTDIR/debs
-    rmdir $ROOTDIR/imgdir
+    if test -z "$DO_FAKECHROOT" ; then
+	umount $ROOTDIR/var/cache/apt/archives
+	umount $ROOTDIR/var/lib/apt/lists
+	for i in debs imgdir ;
+	do
+	    umount $ROOTDIR/$i
+	    rmdir $ROOTDIR/$i
+	done
+    else
+	(cd $ROOTDIR/var/cache/apt/archives ; \
+	 for i in * ; do \
+	     if test ! -f $DIR/var.cache.apt.archives/$i ; then \
+		 echo caching $i ; \
+		 ln $i $DIR/var.cache.apt.archives/ ; \
+	     fi ; \
+	 done)
+	(cd $ROOTDIR/var/lib/apt/lists ; \
+	 for i in * ; do \
+	     if test ! -f $DIR/var.lib.apt.lists/$i ; then \
+		 echo caching $i ; \
+		 ln $i $DIR/var.lib.apt.lists/ ; \
+	     fi ; \
+	 done)
+	find $ROOTDIR/var/cache/apt/archives $ROOTDIR/var/lib/apt/lists \
+	     $ROOTDIR/debs -type f | xargs rm
+	rmdir $ROOTDIR/debs
+	rmdir $ROOTDIR/imgdir
+    fi
     case "$OUT_TAR" in
 	*.gz)	ZCMD="gzip -9n" ;;
 	*)	ZCMD="cat" ;
@@ -323,7 +387,21 @@ if test -n "$OUT_TAR"; then
     (cd "$ROOTDIR" ; find . -print0 | LC_ALL=C sort -z |
 	 tar -c --null --no-recursion -T - --numeric-owner \
 	     --mtime="@${SOURCE_DATE_EPOCH}" -f - | $ZCMD > "$OUT_TAR")
-    cleanup_rootdir
+    if test -z "$DO_FAKECHROOT" ; then
+	umount $ROOTDIR
+	rmdir $ROOTDIR
+	if test "$SAVE_RAW_ROOT" = "yes" ; then
+	    echo "Raw root image has been saved at" $RAW_ROOT_FS
+	else
+	    rm -f $RAW_ROOT_FS
+	fi
+    else
+	if test "$SAVE_RAW_ROOT" = "yes" ; then
+	    echo "Raw root directory has been saved at" $ROOTDIR
+	else
+	    rm -rf $ROOTDIR
+	fi
+    fi
     exit 0
 fi
 
