Teach *-xfstests commands to potentially use lib/xfstests-appliance
Eventually it would be useful to package up kvm-xfstests,
gce-xfstests, and/or android-xfstests into standalone packages.  As a
start, if the script is found in /PATHNAME/bin/foo-xfstests, try to
see if /PATHNAME/lib/xfstests-appliance exists, and if so, use it to
find the various helper scripts.

Signed-off-by: Theodore Ts'o <tytso@mit.edu>

diff --git a/kvm-xfstests/android-xfstests b/kvm-xfstests/android-xfstests
--- a/kvm-xfstests/android-xfstests
+++ b/kvm-xfstests/android-xfstests
@@ -3,9 +3,24 @@
 set -e -o pipefail
 
 XFSTESTS_FLAVOR=android
-DIR=.
-if [ -n "$ANDROID_XFSTESTS_DIR" ]; then
-    DIR="$ANDROID_XFSTESTS_DIR"
+t=$(echo ${XFSTESTS_FLAVOR}_xfstests_dir | tr "[:lower:]" "[:upper:]")
+eval DIR="\$$t"
+if test -z "$DIR"
+then
+    t="$(dirname "$(dirname "$0")")/lib/xfstests-appliance"
+    if test -d "$t"
+    then
+	DIR="$t"
+    fi
+fi
+if test -z "$DIR"
+then
+    DIR=$(pwd)
+fi
+if test ! -f "$DIR/util/get-config"
+then
+    echo "$(basename "$0"): couldn't find $DIR/util/get-config"
+    exit 1
 fi
 
 . "$DIR/util/get-config"
diff --git a/kvm-xfstests/gce-xfstests b/kvm-xfstests/gce-xfstests
--- a/kvm-xfstests/gce-xfstests
+++ b/kvm-xfstests/gce-xfstests
@@ -1,17 +1,27 @@
 #!/bin/bash
 
 XFSTESTS_FLAVOR=gce
-DIR=.
-if test -n "$GCE_XFSTESTS_DIR"
+t=$(echo ${XFSTESTS_FLAVOR}_xfstests_dir | tr "[:lower:]" "[:upper:]")
+eval DIR="\$$t"
+if test -z "$DIR"
 then
-    DIR="$GCE_XFSTESTS_DIR"
+    t="$(dirname "$(dirname "$0")")/lib/xfstests-appliance"
+    if test -d "$t"
+    then
+	DIR="$t"
+    fi
+fi
+if test -z "$DIR"
+then
+    DIR=$(pwd)
+fi
+if test ! -f "$DIR/util/get-config"
+then
+    echo "$(basename "$0"): couldn't find $DIR/util/get-config"
+    exit 1
 fi
 
 . "$DIR/util/get-config"
-
-if test -r "$DIR/test-appliance/config.custom" ; then
-   . "$DIR/test-appliance/config.custom"
-fi
 
 if test -z "$GS_BUCKET" -o -z "$GCE_PROJECT" -o -z "$GCE_ZONE"
 then
@@ -301,16 +311,34 @@ case "$1" in
 	;;
     create-image)
 	shift
+	if test ! -x "$DIR/test-appliance/gce-create-image"
+	then
+	    echo "Image creation not supported in this installation"
+	    exit 1
+	fi
+	export GCE_XFSTESTS_DIR="$DIR"
 	"$DIR/test-appliance/gce-create-image" "$@"
 	exit $?
 	;;
     export-image)
 	shift
+	if test ! -x "$DIR/test-appliance/gce-export-image"
+	then
+	    echo "Image export not supported in this installation"
+	    exit 1
+	fi
+	export GCE_XFSTESTS_DIR="$DIR"
 	"$DIR/test-appliance/gce-export-image" "$@"
 	exit $?
 	;;
     import-image)
 	shift
+	if test ! -x "$DIR/test-appliance/gce-import-image"
+	then
+	    echo "Image import not supported in this installation"
+	    exit 1
+	fi
+	export GCE_XFSTESTS_DIR="$DIR"
 	"$DIR/test-appliance/gce-import-image" "$@"
 	exit $?
 	;;
diff --git a/kvm-xfstests/kvm-xfstests b/kvm-xfstests/kvm-xfstests
--- a/kvm-xfstests/kvm-xfstests
+++ b/kvm-xfstests/kvm-xfstests
@@ -1,10 +1,24 @@
 #!/bin/bash
 
 XFSTESTS_FLAVOR=kvm
-DIR=.
-if test -n "$KVM_XFSTESTS_DIR"
+t=$(echo ${XFSTESTS_FLAVOR}_xfstests_dir | tr "[:lower:]" "[:upper:]")
+eval DIR="\$$t"
+if test -z "$DIR"
 then
-    DIR="$KVM_XFSTESTS_DIR"
+    t="$(dirname "$(dirname "$0")")/lib/xfstests-appliance"
+    if test -d "$t"
+    then
+	DIR="$t"
+    fi
+fi
+if test -z "$DIR"
+then
+    DIR=$(pwd)
+fi
+if test ! -f "$DIR/util/get-config"
+then
+    echo "$(basename "$0"): couldn't find $DIR/util/get-config"
+    exit 1
 fi
 
 . "$DIR/util/get-config"
