{gce,kvm}-xfstests, test-appliance: add support for kernel modules
Allow the kernel to be built with modules.  The modules can either be
found in a modules.tar.xz file located in the top-level kernel
directory, or explicitly specified via the --modules command-line
option used with gce-xfstests or kvm-xfstests.

Signed-off-by: Theodore Ts'o <tytso@mit.edu>

diff --git a/kvm-xfstests/gce-xfstests b/kvm-xfstests/gce-xfstests
--- a/kvm-xfstests/gce-xfstests
+++ b/kvm-xfstests/gce-xfstests
@@ -571,10 +571,7 @@ case "$OVERRIDE_KERNEL" in
 	;;
     "")
 	GS_KERNEL=gs://$GS_BUCKET/bzImage
-	if test -z "$GCE_KERNEL"
-	then
-	    GCE_KERNEL=$KERNEL
-	fi
+	GCE_KERNEL=$KERNEL
 	;;
     *)
 	GCE_KERNEL=$OVERRIDE_KERNEL
@@ -669,6 +666,53 @@ then
     fi
     ARG="$ARG tarfiles=$GS_FILES"
     rm -f "$LOCAL_FILES"
+fi
+
+case "$OVERRIDE_MODULES" in
+    gs://*)
+	GS_MODULES="$OVERRIDE_MODULES"
+	GCE_MODULES=""
+	;;
+    "")
+	if test -n "$MODULES" ; then
+	    GS_MODULES="gs://$GS_BUCKET/modules.tar.xz"
+	    GCE_MODULES="$MODULES";
+	fi
+	;;
+    *)
+	GCE_MODULES="$OVERRIDE_MODULES"
+	if test -z "$OVERRIDE_MODULES" ; then
+	    GS_MODULES="gs://$GS_BUCKET/modules.tar.xz"
+	elif test -n "$RUN_ON_LTM"; then
+	    # every shard will have to download the image. changing the
+	    # -onetime tag is necessary to not cause the first shard to attempt
+	    # to delete the image.
+	    GS_MODULES="gs://$GS_BUCKET/modules-$TESTRUNID-onerun"
+	else
+	    GS_MODULES="gs://$GS_BUCKET/modules-$TESTRUNID-onetime"
+	fi
+	;;
+esac
+
+if [ -z "$NO_ACTION" -a -n "$GCE_MODULES" ] || \
+   [ -n "$RUN_ON_LTM" -a -n "$GCE_MODULES" ]
+then
+    if ! test -f "$GCE_MODULES"
+    then
+	echo "Can't find modules at $GCE_MODULES"
+	exit 1
+    fi
+    get_local_hash "$GCE_MODULES"
+    get_remote_hash "$GS_MODULES"
+    if test "$LOCAL_HASH" != "$REMOTE_HASH"
+    then
+	gsutil cp "$GCE_MODULES" "$GS_MODULES"
+    fi
+fi
+
+if test -n "$GS_MODULES"
+then
+    ARG="$ARG tarmodules=$GS_MODULES"
 fi
 
 if test -n "$GS_KERNEL"
diff --git a/kvm-xfstests/util/parse_cli b/kvm-xfstests/util/parse_cli
--- a/kvm-xfstests/util/parse_cli
+++ b/kvm-xfstests/util/parse_cli
@@ -173,6 +173,17 @@ validate_config_name()
     fi
 }
 
+if flavor_in gce && test -n "$GCE_KERNEL" ; then
+    KERNEL="$GCE_KERNEL"
+fi
+
+if test -d "$KERNEL" ; then
+    if test -f "$KERNEL/modules.tar.xz" ; then
+	MODULES="$KERNEL/modules.tar.xz"
+    fi
+    KERNEL="$KERNEL/arch/x86/boot/bzImage"
+fi
+
 shortopts="ac:C:g:hI:m:n:No:O:r:vx:X:"
 longopts=(
 aio:
@@ -192,6 +203,7 @@ kernel:
 local-ssd
 log
 machtype:
+modules:
 no-action
 no-archive
 no-collapse
@@ -375,9 +387,40 @@ while (( $# >= 1 )); do
 	--kernel) shift
 	    KERNEL="$1"
 	    if test -d "$KERNEL" ; then
+		if test -z "$OVERRIDE_MODULES" ; then
+		    if test -f "$KERNEL/modules.tar.xz" ; then
+			MODULES="$KERNEL/modules.tar.xz"
+			OVERRIDE_MODULES="$MODULES"
+		    else
+			MODULES=""
+		    fi
+		fi
 		KERNEL="$KERNEL/arch/x86/boot/bzImage"
 	    fi
 	    OVERRIDE_KERNEL="$KERNEL"
+	    ;;
+	--modules) shift
+	    supported_flavors kvm gce
+	    case "$1" in
+		gs://*)
+		    MODULES="$1"
+		    ;;
+		//*)
+		    MODULES=$(echo "$1" | sed -e "s;//;gs://$GS_BUCKET/;")
+		    ;;
+		none)
+		    MODULES=""
+		    ;;
+		*)
+		    if test -f "$1" ; then
+			MODULES="$1"
+		    else
+			echo "Can't find modules at $1"
+			exit 1
+		    fi
+		    ;;
+	    esac
+	    OVERRIDE_MODULES="$MODULES";
 	    ;;
 	--initrd) shift
 	    supported_flavors kvm
@@ -695,10 +738,6 @@ fi
 
 if test "$NO_ZERO" = yes ; then
     FSTESTOPT="$FSTESTOPT,no_zero"
-fi
-
-if test -d "$KERNEL" ; then
-    KERNEL="$KERNEL/arch/x86/boot/bzImage"
 fi
 
 FSTESTOPT=${FSTESTOPT/#,/}
