kvm-xfstests: check to make sure VD[BDDEFG] exist
If there is a config file error and the VD? variables reference a
non-existent device/file, bail out early with an error.

Signed-off-by: Theodore Ts'o <tytso@mit.edu>

diff --git a/kvm-xfstests/kvm-xfstests b/kvm-xfstests/kvm-xfstests
--- a/kvm-xfstests/kvm-xfstests
+++ b/kvm-xfstests/kvm-xfstests
@@ -42,6 +42,15 @@ then
 	$DIR/setup
 fi
 
+for i in "$VDB" "$VDC" "$VDD" "$VDE" "$VDF" "$VDG"
+do
+    if ! test -e "$i"
+    then
+	echo "Fatal error: disk $i does not exit.  Config error?"
+	exit 1;
+    fi
+done
+
 if ionice -h > /dev/null ; then
     IONICE="ionice -n 5"
 fi
