test-appliance: unify the .deb/bzImage kernel load path in the GCE Test VM
The way the test parametsr were passed when loading a kernel.deb was
different from what was used by kvm-xfstess and gce-xfstests with
kexec.  Unfortunately the kernel.deb load path didn't support passing
kernel options to the kernel under test --- which is needed when
testing DAX, and when the developer uses the gce-xfstests options -n,
-r, or -o.

There was also a bug in the kernel.deb path where fstestapi was not
correctly getting split, which caused warnings when the test VM was
attempting to validate the test API version.

We now set the kernel boot command line options via
GRUB_CMDLINE_LINUX, so there is a consistent way of plumbing test
parameters to the kernel under test.

Fixes: fae31d5cafa3 ("test-appliance: add support to boot kernel via deb")
Signed-off-by: Theodore Ts'o <tytso@mit.edu>

diff --git a/kvm-xfstests/test-appliance/files/usr/local/lib/gce-load-kernel b/kvm-xfstests/test-appliance/files/usr/local/lib/gce-load-kernel
--- a/kvm-xfstests/test-appliance/files/usr/local/lib/gce-load-kernel
+++ b/kvm-xfstests/test-appliance/files/usr/local/lib/gce-load-kernel
@@ -8,36 +8,7 @@
 
 . /usr/local/lib/gce-funcs
 
-kernel_deb=$(gce_attribute kexec)
-if [[ $kernel_deb == *.deb ]] ; then
-    skip_kexec=1
-    if ! test -f "/root/kernel-deb.deb" ; then
-	if ! gsutil cp $kernel_deb /root/kernel-deb.deb ; then
-	    echo "gsutil cp $kernel_deb /root/kernel-deb.deb failed"
-	    exit 1
-	fi
-	retry=0
-	while ! dpkg -i /root/kernel-deb.deb ; do
-	    sleep 5
-	    (( retry++ ))
-	    if test "$retry" -gt 36 ; then
-		logger "Kernel installation failed after multiple retries"
-		exit 1
-	    fi
-	done
-	logger "Installation succeeded ($retry retries required)"
-	kernel=$(dpkg -c kernel-deb.deb  | grep "vmlinuz" | rev | cut -d "/" -f1 | rev | cut -d "-" -f2-)
-	menuline=$(grep -i "menuentry '" /boot/grub/grub.cfg|sed -r "s|--class .*$||g" | grep -ne $kernel | grep -v recovery | cut -f1 -d":")
-	menunum=$(($menuline-2))
-	grub-reboot "1>$menunum"
-	echo "Rebooting..."
-	reboot
-    fi
-fi
-
-if test -z "$skip_kexec" ; then
-    if grep -q fstestcfg /proc/cmdline; then exit 0; fi
-fi
+if grep -q fstestcfg /proc/cmdline; then exit 0; fi
 
 if test -f /root/do_kexec ; then
     /usr/local/lib/gce-logger do_kexec file found, using it
@@ -129,20 +100,6 @@ EOF
     exit 0
 fi
 
-if test -n "$skip_kexec" ; then
-    exit 0
-fi
-
-if ! test -f /root/bzImage
-then
-    if ! gsutil cp $kexec /root/bzImage
-    then
-	logger "Couldn't find $kexec"
-	exit 1
-    fi
-    sync
-fi
-
 if test -n "$fstesttz" -a -f /usr/share/zoneinfo/$fstesttz
 then
     ln -sf /usr/share/zoneinfo/$fstesttz /etc/localtime
@@ -174,12 +131,55 @@ then
     kopt="$kopt pts_size=$pts_size"
 fi
 
+kopt="console=ttyS0,115200 earlyprintk=ttyS0,115200 elevator=noop console=ttyS0 net.ifnames=0 biosdevname=0 $kopt fstestcfg=$fstestcfg fstestset=$fstestset fstestexc=$fstestexc fstestopt=$fstestopt fstesttyp=$fstesttyp fstestapi=$fstestapi fsteststr=$fsteststr nfssrv=$nfssrv orig_cmdline=$orig_cmdline"
+
+if [[ $kexec == *.deb ]] ; then
+    cat > /etc/default/grub.d/50-xfstests-cmd.cfg <<EOF
+# This file was generated by /usr/local/lib/gce-load-kernel
+
+GRUB_CMDLINE_LINUX="$kopt"
+EOF
+    if ! test -f "/root/kernel-deb.deb" ; then
+	if ! gsutil cp $kexec /root/kernel-deb.deb ; then
+	    echo "gsutil cp $kexec /root/kernel-deb.deb failed"
+	    exit 1
+	fi
+    fi
+    retry=0
+    while ! dpkg -i /root/kernel-deb.deb ; do
+	sleep 5
+	(( retry++ ))
+	if test "$retry" -gt 36 ; then
+	    logger "Kernel installation failed after multiple retries"
+	    exit 1
+	fi
+    done
+    logger "Installation succeeded ($retry retries required)"
+    kernel=$(dpkg -c /root/kernel-deb.deb  | grep "vmlinuz" | rev | cut -d "/" -f1 | rev | cut -d "-" -f2-)
+    menuline=$(grep -i "menuentry '" /boot/grub/grub.cfg|sed -r "s|--class .*$||g" | grep -ne $kernel | grep -v recovery | cut -f1 -d":")
+    menunum=$(($menuline-2))
+    logger "Using grub-reboot 1>$menunum"
+    grub-reboot "1>$menunum"
+    echo "Rebooting..."
+    reboot
+fi
+
+if ! test -f /root/bzImage
+then
+    if ! gsutil cp $kexec /root/bzImage
+    then
+	logger "Couldn't find $kexec"
+	exit 1
+    fi
+    sync
+fi
+
 cat > /root/do_kexec <<EOF
 run_hooks kexec
 /usr/local/lib/gce-logger kexec to test kernel
 systemctl stop rsyslog.service
 sync
-kexec /root/bzImage --command-line="root=/dev/sda1 ro console=ttyS0,38400n8 elevator=noop net.ifnames=0 biosdevname=0 console=ttyS0 $kopt fstestcfg=$fstestcfg fstestset=$fstestset fstestexc=$fstestexc fstestopt=$fstestopt fstesttyp=$fstesttyp fstestapi=$fstestapi fsteststr=$fsteststr nfssrv=$nfssrv orig_cmdline=$orig_cmdline"
+kexec /root/bzImage --command-line="root=/dev/sda1 ro $kopt"
 /usr/local/lib/gce-logger kexec failed?!?
 exit 1
 EOF
