test-appliance: allow the GCE instance to be cleanly stopped and re-started
Instead of using /run, store various state files in
/var/lib/gce-xfstests and the kexec kernel in /root so the VM can be
stopped and then restarted.

Signed-off-by: Theodore Ts'o <tytso@mit.edu>

diff --git a/kvm-xfstests/test-appliance/files/usr/local/lib/gce-parse b/kvm-xfstests/test-appliance/files/usr/local/lib/gce-parse
--- a/kvm-xfstests/test-appliance/files/usr/local/lib/gce-parse
+++ b/kvm-xfstests/test-appliance/files/usr/local/lib/gce-parse
@@ -20,10 +20,14 @@ fi
 kexec=$(gce_attribute kexec)
 if test -z "$kexec" || grep -q fstestcfg /proc/cmdline; then exit 0; fi
 
-if ! gsutil cp $kexec /run/bzImage
+if ! test -f /root/bzImage
 then
-    logger "Couldn't find $kexec"
-    exit 1
+    if ! gsutil cp $kexec /root/bzImage
+    then
+	logger "Couldn't find $kexec"
+	exit 1
+    fi
+    sync
 fi
 
 kopt=$(gce_attribute kopt)
@@ -46,4 +50,4 @@ then
     kopt="$kopt maxcpus=$cpus"
 fi
 
-kexec /run/bzImage --command-line="root=/dev/sda1 ro console=ttyS0,38400n8 elevator=noop console=ttyS0 $kopt fstestcfg=$fstestcfg fstestset=$fstestset fstestopt=$fstestopt fstesttz=$fstesttz fstesttyp=$fstesttyp fstestapi=$fstestapi"
+kexec /root/bzImage --command-line="root=/dev/sda1 ro console=ttyS0,38400n8 elevator=noop console=ttyS0 $kopt fstestcfg=$fstestcfg fstestset=$fstestset fstestopt=$fstestopt fstesttz=$fstesttz fstesttyp=$fstesttyp fstestapi=$fstestapi"
